version: '3'

services:
  backend:
    image: node:13
    command: yarn workspace @typus/backend start
    ports:
      - 4000:4000
    volumes:
      - .:/srv/backend:rw
    working_dir: /srv/backend
    depends_on:
      - redis
      - postgres
      - elastic
    networks:
    - postgres
    - redis
    - elastic

  frontend:
    tty: true
    image: node:13
    command: yarn workspace @typus/frontend start
    ports:
        - 3000:3000
    volumes:
        - .:/srv/frontend:rw
    working_dir: /srv/frontend
    depends_on:
        - backend

  postgres:
    image: postgres
    restart: always
    networks:
      - postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'typus'
      POSTGRES_PASSWORD: abc123
      PGPORT: 5432
    volumes:
      - 'postgres_data:/postgres/data'
    ports: 
      - 5432:5432

  redis:
    image: bitnami/redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    networks:
      - redis
    volumes:
        - 'redis_data:/redis/data'

  elastic:
    image: blacktop/elasticsearch
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elastic
    ports:
      - '9200:9200'
    volumes:
      - 'elastic_data:/elastic/data'

volumes:
  redis_data:
  postgres_data:
  elastic_data:

networks:
  redis:
  postgres:
  elastic:
