version: '3'

services:
  app:
    image: node:13
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - postgres
      - redis
      - elasticsearch
    networks:
      - postgres
      - redis
      - elastic
    environment:
      NODE_ENV: development
    ports:
      - 4000:4000
    command: npm run start

  postgres:
    image: postgres
    restart: always
    networks:
      - postgres
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'typus'
      POSTGRES_PASSWORD: abc123
      PGPORT: 5432
    volumes:
      - 'postgres_data:/postgres/data'
    ports: 
      - 5432:5432

  redis:
    image: bitnami/redis:5.0
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    networks:
      - redis
    volumes:
        - 'redis_data:/redis/data'

  elasticsearch:
    image: blacktop/elasticsearch
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elastic
    ports:
      - '9200:9200'
    volumes:
      - 'elastic_data:/elastic/data'

volumes:
  redis_data:
  postgres_data:
  elastic_data:

networks:
  redis:
  postgres:
  elastic:
